services:
  shortener:
    container_name: shortener
    tty: true
    image: franjb/shortener:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres:/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

volumes:
  postgres:
